//? home imports
import Head from "next/head";
import cars from "@/data/carsData";
//? import components
import CarCard from "@/components/CarCard";

export default function Home() {
  const top5 = cars.slice(0, 5);
  return (
    <>
      <Head>
        <title>Car Dealership</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <div className="wrapper">
          <div className="grid">
            {top5.map((car, i) => (
              <div key={i}>
                <CarCard car={car} />
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
